name: Helper

on:
  pull_request:
    types:
      - closed

jobs:
  instructions:
    name: instructions
    runs-on: ubuntu-latest
    steps:
       - run: curl https://notify-api.is-a.dev/pr/merged/${{ github.event.pull_request.number }}
