name: PR

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "closed"]

jobs:
  opened:
    if: github.event.action == 'opened'
    name: "Opened"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Comment"
        uses: mshick/add-pr-comment@v2
        with:
          message-path: ".github/comments/opened.md"
          proxy-url: https://register.is-a.dev

  closed:
    if: github.event.action == 'closed' && github.event.pull_request.merged == false
    name: "Closed"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Comment"
        uses: mshick/add-pr-comment@v2
        with:
          message-path: ".github/comments/closed.md"
          proxy-url: https://register.is-a.dev

  merged:
    if: github.event.pull_request.merged == true
    name: "Merged"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Comment"
        uses: mshick/add-pr-comment@v2
        with:
          message-path: ".github/comments/merged.md"
          proxy-url: https://register.is-a.dev
